# EDA for CRMLS Listed and Sold Data

- **Listed transactions**
- **Sold transactions**

In [1]:
import pandas as pd
import glob
import os

pd.set_option("display.max_columns", 100)

In [2]:
listed_files = sorted(glob.glob("data/CRMLSListing*.csv"))
sold_files = sorted(glob.glob("data/CRMLSSold*.csv"))

print("Listed files found:", len(listed_files))
for f in listed_files:
    print(" -", os.path.basename(f))

print("\nSold files found:", len(sold_files))
for f in sold_files:
    print(" -", os.path.basename(f))

Listed files found: 27
 - CRMLSListing202401.csv
 - CRMLSListing202402.csv
 - CRMLSListing202403.csv
 - CRMLSListing202404.csv
 - CRMLSListing202405.csv
 - CRMLSListing202406.csv
 - CRMLSListing202407.csv
 - CRMLSListing202408.csv
 - CRMLSListing202409.csv
 - CRMLSListing202410.csv
 - CRMLSListing202411.csv
 - CRMLSListing202412.csv
 - CRMLSListing202501.csv
 - CRMLSListing202502.csv
 - CRMLSListing202503.csv
 - CRMLSListing202504.csv
 - CRMLSListing202505.csv
 - CRMLSListing202506.csv
 - CRMLSListing202507.csv
 - CRMLSListing202508.csv
 - CRMLSListing202509.csv
 - CRMLSListing202510.csv
 - CRMLSListing202511.csv
 - CRMLSListing202512.csv
 - CRMLSListing202601.csv
 - CRMLSListing202602.csv
 - CRMLSListing202603.csv

Sold files found: 27
 - CRMLSSold202401.csv
 - CRMLSSold202402.csv
 - CRMLSSold202403.csv
 - CRMLSSold202404.csv
 - CRMLSSold202405.csv
 - CRMLSSold202406.csv
 - CRMLSSold202407.csv
 - CRMLSSold202408.csv
 - CRMLSSold202409.csv
 - CRMLSSold202410.csv
 - CRMLSSold202411.csv
 - CRMLSSold202412.csv
 - CRMLSSold202501.csv
 - CRMLSSold202502.csv
 - CRMLSSold202503.csv
 - CRMLSSold202504.csv
 - CRMLSSold202505.csv
 - CRMLSSold202506.csv
 - CRMLSSold202507.csv
 - CRMLSSold202508.csv
 - CRMLSSold202509.csv
 - CRMLSSold202510.csv
 - CRMLSSold202511.csv
 - CRMLSSold202512.csv
 - CRMLSSold202601.csv
 - CRMLSSold202602.csv
 - CRMLSSold202603.csv

In [3]:
len(listed_files), len(sold_files)

(27, 27)

In [4]:
if not listed_files:
    raise FileNotFoundError("No listing CSV files were found in data/.")
if not sold_files:
    raise FileNotFoundError("No sold CSV files were found in data/.")

## 2. Load and append all months

In [5]:
df_listed = pd.concat([pd.read_csv(file) for file in listed_files], ignore_index=True)
df_sold = pd.concat([pd.read_csv(file) for file in sold_files], ignore_index=True)

print("Combined listed shape:", df_listed.shape)
print("Combined sold shape:", df_sold.shape)

Combined listed shape: (239785, 81)
Combined sold shape: (175206, 79)

In [6]:
df_listed.head(20)

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,DaysOnMarket,ListOfficeName,BuyerOfficeName,CoListOfficeName,ListAgentFullName,CoListAgentFirstName,CoListAgentLastName,BuyerAgentMlsId,BuyerAgentFirstName,BuyerAgentLastName,FireplacesTotal,AssociationFeeFrequency,AboveGradeFinishedArea,ListingKeyNumeric,MLSAreaMajor,TaxAnnualAmount,CountyOrParish,PropertyType.1,MlsStatus,ElementarySchool,ListAgentFirstName.1,AttachedGarageYN,ParkingTotal,BuilderName,PropertySubType,LotSizeAcres,SubdivisionName,BuyerOfficeAOR,YearBuilt,DaysOnMarket.1,StreetNumberNumeric,LivingArea.1,ListingId,BathroomsTotalInteger,City,TaxYear,BuildingAreaTotal,BedroomsTotal,ContractStatusChangeDate,Longitude.1,ElementarySchoolDistrict,CoBuyerAgentFirstName,PurchaseContractDate,ListingContractDate,BelowGradeFinishedArea,BusinessType,Latitude.1,ListPrice.1,StateOrProvince,CoveredSpaces,MiddleOrJuniorSchool,FireplaceYN,Stories,HighSchool,Levels,ListAgentLastName.1,CloseDate.1,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,1498000.0,1156830188,NaN,NaN,Susan,Vega,33.630408,-117.694901,22871 Willard,Residential,2403.0,1498000.0,0,Realty One Group West,NaN,NaN,Susan Vega,NaN,NaN,NaN,NaN,NaN,NaN,Monthly,NaN,1156830188,LS - Lake Forest South,NaN,Orange,Residential,ComingSoon,NaN,Susan,True,2.0,NaN,SingleFamilyResidence,0.2184,NaN,NaN,1965.0,0,22871.0,2403.0,OC26065585,3.0,Lake Forest,NaN,NaN,4.0,2026-04-09,-117.694901,NaN,NaN,NaN,2026-02-25,NaN,NaN,33.630408,1498000.0,CA,NaN,NaN,True,1.0,NaN,One,Vega,NaN,NaN,9513.00,4.0,False,2.0,Saddleback Valley Unified,92630,NaN,132.00,9513.0,NaN,22871 Willard
1,1068000.0,1156828950,NaN,NaN,glenn,hammerburg,36.697911,-119.549810,1240 J Street,ResidentialIncome,NaN,1068000.0,0,Realty Fresno,NaN,NaN,glenn hammerburg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1156828950,FSNO - Fresno,NaN,Fresno,ResidentialIncome,Active,NaN,glenn,NaN,7.0,NaN,Apartment,0.3300,Not Applicable,NaN,1930.0,0,1240.0,NaN,V1-35600,0.0,Sanger,NaN,5242.0,NaN,2026-02-03,-119.549810,NaN,NaN,NaN,2026-02-03,NaN,NaN,36.697911,1068000.0,CA,NaN,NaN,False,NaN,NaN,NaN,hammerburg,NaN,NaN,14374.00,NaN,True,0.0,NaN,93657,NaN,0.00,14374.0,NaN,1240 J Street
2,1980000.0,1156824533,NaN,NaN,Affie,Setoodeh,33.980656,-117.522061,5930 Etiwanda,CommercialSale,NaN,1980000.0,0,CENTURY 21 Affiliated,NaN,NaN,Affie Setoodeh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1156824533,251 - Jurupa Valley,NaN,Riverside,CommercialSale,Active,NaN,Affie,NaN,10.0,NaN,MixedUse,2.6600,NaN,NaN,1952.0,0,5930.0,NaN,OC26072856,NaN,Jurupa Valley,NaN,3230.0,NaN,2026-02-26,-117.522061,NaN,NaN,NaN,2026-02-26,NaN,NaN,33.980656,1980000.0,CA,NaN,NaN,NaN,NaN,NaN,NaN,Setoodeh,NaN,NaN,115870.00,NaN,NaN,NaN,NaN,91752,NaN,NaN,115870.0,NaN,5930 Etiwanda
3,499000.0,1156818465,NaN,NaN,Keersten,Milson,33.976312,-116.522054,65352 Rolling Hills,Residential,2089.0,499000.0,0,Capitis Real Estate,NaN,NaN,Keersten Milson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1156818465,341 - Mission Lakes,NaN,Riverside,Residential,Active,NaN,Keersten,True,2.0,NaN,SingleFamilyResidence,0.2100,Mission Lakes (34101),NaN,2020.0,0,65352.0,2089.0,JT26072467,3.0,Desert Hot Springs,NaN,NaN,4.0,2026-02-03,-116.522054,NaN,NaN,NaN,2026-02-03,NaN,NaN,33.976312,499000.0,CA,NaN,NaN,False,1.0,NaN,One,Milson,NaN,NaN,9148.00,4.0,False,2.0,Palm Springs Unified,92240,NaN,0.00,9148.0,NaN,65352 Rolling Hills
4,5500.0,1156816107,NaN,NaN,Nicholas,Cosfol,34.131821,-118.340211,3121 Lake Hollywood Drive,ResidentialLease,1357.0,5500.0,0,Property Masters Realty,NaN,NaN,Nicholas Cosfol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1156816107,C30 - Hollywood Hills East,NaN,Los Angeles,ResidentialLease,Active,NaN,Nicholas,True,1.0,NaN,SingleFamilyResidence,0.1732,Not Applicable,NaN,1948.0,0,3121.0,1357.0,P1-26556,2.0,Los Angeles,NaN,NaN,2.0,2026-02-17,-118.340211,NaN,NaN,NaN,2026-02-17,NaN,NaN,34.131821,5500.0,CA,NaN,NaN,True,1.0,NaN,One,Cosfol,NaN,NaN,7543.00,NaN,NaN,1.0,NaN,90068,NaN,0.00,7543.0,NaN,3121 Lake Hollywood Drive
5,1195000.0,1156812825,NaN,NaN,David,Duncan,33.485133,-117.681863,25692 Paseo Colonial,Residential,1210.0,1195000.0,0,Fathom Realty Group Inc.,NaN,NaN,David Duncan,NaN,NaN,NaN,NaN,NaN,NaN,Monthly,NaN,1156812825,DO - Del Obispo,NaN,Orange,Residential,ComingSoon,Del Obispo,David,True,4.0,NaN,SingleFamilyResidence,0.0556,Harbor Lane (HL),NaN,1973.0,0,25692.0,1210.0,PW26032885,2.0,San Juan Capistrano,NaN,NaN,3.0,2026-04-10,-117.681863,NaN,NaN,NaN,2026-02-12,0.0,NaN,33.485133,1195000.0,CA,NaN,Marco Forester,True,2.0,San Juan Hills,Two,Duncan,NaN,NaN,2420.00,0.0,False,2.0,Capistrano Unified,92675,NaN,130.00,2420.0,NaN,25692 Paseo Colonial
6,675000.0,1156808971,NaN,NaN,Mario,Garduno,32.615724,-117.045186,1221 Melrose Ave,Residential,1040.0,675000.0,0,Century 21 Affiliated,NaN,NaN,Mario Garduno,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1156808971,91911 - Chula Vista,NaN,San Diego,Residential,Active,NaN,Mario,NaN,4.0,NaN,SingleFamilyResidence,NaN,Chula Vista,NaN,1959.0,0,1221.0,1040.0,260007933SD,2.0,Chula Vista,NaN,NaN,3.0,2026-02-04,-117.045186,NaN,NaN,NaN,2026-02-04,NaN,NaN,32.615724,675000.0,CA,NaN,NaN,False,1.0,NaN,One,Garduno,NaN,NaN,NaN,NaN,False,0.0,NaN,91911,NaN,NaN,NaN,NaN,1221 Melrose Ave
7,1235000.0,1156807420,2026-04-03,1235000.0,Ariel,Belkin,34.092963,-118.337298,6737 W Hepburn,Residential,1956.0,1235000.0,0,The One Luxury Properties,The One Luxury Properties,NaN,Ariel Belkin,NaN,NaN,PF25321m,Ariel,Belkin,NaN,Monthly,NaN,1156807420,C20 - Hollywood,NaN,Los Angeles,Residential,Closed,NaN,Ariel,True,2.0,NaN,SingleFamilyResidence,0.0416,NaN,PasadenaFoothills,2014.0,0,6737.0,1956.0,PF26072555,4.0,Los Angeles,NaN,NaN,3.0,2026-04-03,-118.337298,NaN,NaN,2026-04-03,2026-02-22,NaN,NaN,34.092963,1235000.0,CA,NaN,NaN,False,NaN,NaN,ThreeOrMore,Belkin,2026-04-03,NaN,1814.00,0.0,False,2.0,Los Angeles Unified,90038,The One Luxury Properties,350.00,1814.0,NaN,6737 W Hepburn
8,1150000.0,1156803925,NaN,NaN,Noa,Bolozky,34.124028,-118.194240,5681 Fallston Street,Residential,1147.0,1150000.0,1,Coldwell Banker Realty,NaN,NaN,Noa Bolozky,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1156803925,632 - Highland Park,NaN,Los Angeles,Residential,Active,NaN,Noa,True,2.0,NaN,SingleFamilyResidence,0.1607,NaN,NaN,1978.0,1,5681.0,1147.0,P1-26555,2.0,Los Angeles,NaN,NaN,3.0,2026-02-04,-118.194240,NaN,NaN,NaN,2026-02-04,NaN,NaN,34.124028,1150000.0,CA,NaN,NaN,True,1.0,NaN,One,Bolozky,NaN,NaN,7000.00,NaN,NaN,1.0,NaN,90042,NaN,NaN,7000.0,NaN,5681 Fallston Street
9,308500.0,1156798087,NaN,NaN,Tina,Chao,33.606825,-117.716914,389 Avenida Castilla Q,Residential,1040.0,308500.0,1,Rainbow Realty,NaN,NaN,Tina Chao,NaN,NaN,NaN,NaN,NaN,NaN,Monthly,NaN,1156798087,LW - Laguna Woods,NaN,Orange,Residential,Active,NaN,Tina,NaN,0.0,NaN,StockCooperative,0.0239,Leisure World (LW),NaN,1965.0,1,389.0,1040.0,OC26042352,2.0,Laguna Woods,NaN,NaN,2.0,2026-02-26,-117.716914,NaN,NaN,NaN,2026-02-26,NaN,NaN,33.606825,308500.0,CA,NaN,NaN,False,2.0,NaN,Two,Chao,NaN,NaN,1040.00,2.0,False,0.0,Capistrano Unified,92637,NaN,826.78,1040.0,NaN,389 Avenida Castilla Q
10,659000.0,1156795119,NaN,NaN,Cheri,Jacques,33.960982,-117.228876,24856 Sunday,Residential,1980.0,659000.0,0,CAPITIS REAL ESTATE,NaN,NaN,Cheri Jacques,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1156795119,259 - Moreno Valley,NaN,Riverside,Residential,ComingSoon,NaN,Cheri,True,4.0,NaN,SingleFamilyResidence,0.3100,NaN,NaN,1986.0,0,24856.0,1980.0,IG26072416,2.0,Moreno Valley,NaN,NaN,5.0,2026-04-13,-117.228876,NaN,NaN,NaN,2026-02-02,NaN,NaN,33.960982,659000.0,CA,NaN,NaN,True,1.0,NaN,One,Jacques,NaN,NaN,13504.00,4.0,False,2.0,Moreno Valley Unified,92557,NaN,0.00,13504.0,NaN,24856 Sunday
11,1980000.0,1156794704,NaN,NaN,Affie,Setoodeh,33.980656,-117.522061,5930 Etiwanda,ResidentialIncome,NaN,1980000.0,0,CENTURY 21 Affiliated,NaN,NaN,Affie Setoodeh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1156794704,251 - Jurupa Valley,NaN,Riverside,ResidentialIncome,Active,NaN,Affie,NaN,2.0,NaN,SingleFamilyResidence,2.6600,NaN,NaN,1952.0,0,5930.0,NaN,OC26063800,NaN,Jurupa Valley,NaN,3230.0,NaN,2026-02-18,-117.522061,NaN,NaN,NaN,2026-02-18,NaN,NaN,33.980656,1980000.0,CA,NaN,NaN,False,1.0,NaN,One,Setoodeh,NaN,NaN,115870.00,NaN,False,2.0,NaN,91752,NaN,0.00,115870.0,NaN,5930 Etiwanda
12,2950000.0,1156794701,NaN,NaN,Troy,Gray,35.283041,-120.707219,35 Blarney,Residential,5398.0,2950000.0,2,Kestly Realty Group Inc.,NaN,Kestly Realty Group Inc.,Troy Gray,Jeannie,Pleasant,NaN,NaN,NaN,NaN,NaN,NaN,1156794701,SLO - San Luis Obispo,NaN,San Luis Obispo,Residential,Active,Bishop's Peak,Troy,NaN,0.0,NaN,Quadruplex,4.7800,San Luis Obispo(380),NaN,1930.0,2,35.0,5398.0,SC26072122,7.0,San Luis Obispo,NaN,NaN,14.0,2026-02-12,-120.707219,NaN,NaN,NaN,2026-02-12,NaN,NaN,35.283041,2950000.0,CA,NaN,Laguna,False,1.0,San Luis Obispo,One,Gray,NaN,200x1028,208217.00,14.0,False,0.0,San Luis Coastal Unified,93405,NaN,0.00,208217.0,NaN,35 Blarney
13,799000.0,1156793255,NaN,NaN,Crystal,Pierce,32.812989,-116.932069,1284 Tangerine Street,Residential,1152.0,799000.0,0,ERA Ranch & Sea Realty,NaN,NaN,Crystal Pierce,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1156793255,92021 - El Cajon,NaN,San Diego,Residential,Active,NaN,Crystal,True,2.0,NaN,SingleFamilyResidence,0.1400,NaN,NaN,1959.0,0,1284.0,1152.0,NDP2603225,2.0,El Cajon,NaN,NaN,3.0,2026-02-10,-116.932069,NaN,NaN,NaN,2026-02-10,NaN,NaN,32.812989,799000.0,CA,NaN,NaN,True,1.0,NaN,One,Pierce,NaN,NaN,0.14,NaN,NaN,2.0,Grossmont Union,92021,NaN,0.00,6098.4,NaN,1284 Tangerine Street
14,589000.0,1156792567,NaN,NaN,KAREN,AAKER,34.029571,-117.336011,177 Maria Court,Residential,1852.0,589000.0,0,EXP REALTY OF SOUTHERN CALIFORNIA INC.,NaN,NaN,KAREN AAKER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1156792567,273 - Colton,NaN,San Bernardino,Residential,ComingSoon,Wilson,KAREN,True,5.0,NaN,SingleFamilyResidence,0.2314,NaN,NaN,1979.0,0,177.0,1852.0,IV26071393,3.0,Colton,NaN,NaN,4.0,2026-04-11,-117.336011,NaN,NaN,NaN,2026-02-11,NaN,NaN,34.029571,589000.0,CA,NaN,Terrace Hills,True,2.0,Grand Terrace,Two,AAKER,NaN,NaN,10080.00,1.0,False,2.0,Colton Unified,92324,NaN,0.00,10080.0,NaN,177 Maria Court
15,839000.0,1156789232,2026-03-30,820000.0,Jin,Qi,33.735718,-117.781744,2813 2813 Player Lane,Residential,1190.0,839000.0,0,Realty One Group West,Realty One Group West,NaN,Jin Qi,NaN,NaN,sqijin,Jin,Qi,NaN,Monthly,NaN,1156789232,89 - Tustin Ranch,NaN,Orange,Residential,Closed,NaN,Jin,True,2.0,NaN,Townhouse,0.0230,Tustin Del Verde,OrangeCounty,1999.0,0,2813.0,1190.0,OC26072248,2.0,Tustin,NaN,NaN,2.0,2026-03-30,-117.781744,NaN,NaN,2026-03-27,2026-02-19,NaN,NaN,33.735718,839000.0,CA,NaN,NaN,True,NaN,NaN,ThreeOrMore,Qi,2026-03-30,NaN,1000.00,0.0,False,2.0,Tustin Unified,92782,Realty One Group West,495.00,1000.0,NaN,2813 2813 Player Lane
16,849000.0,1156786199,NaN,NaN,Mike,Stine,33.354725,-117.149782,35647 Garrano Lane,Residential,2285.0,849000.0,0,eXp Realty of Southern CA,NaN,NaN,Mike Stine,NaN,NaN,NaN,NaN,NaN,NaN,Monthly,NaN,1156786199,92028 - Fallbrook,NaN,San Diego,Residential,ComingSoon,NaN,Mike,True,6.0,NaN,SingleFamilyResidence,0.1700,NaN,NaN,2018.0,0,35647.0,2285.0,NDP2603222,3.0,Fallbrook,NaN,NaN,3.0,2026-04-10,-117.149782,NaN,NaN,NaN,2026-02-28,NaN,NaN,33.354725,849000.0,CA,NaN,NaN,False,2.0,NaN,Two,Stine,NaN,NaN,0.17,2.0,NaN,2.0,Fallbrook Union,92028,NaN,208.00,7405.2,NaN,35647 Garrano Lane
17,1870000.0,1156784075,NaN,NaN,Marcel,Hensley,33.532988,-117.198587,25824 Long Acres,Residential,4259.0,1870000.0,0,KW Temecula,NaN,NaN,Marcel Hensley,NaN,NaN,NaN,NaN,NaN,NaN,Monthly,NaN,1156784075,SRCAR - Southwest Riverside County,NaN,Riverside,Residential,Pending,NaN,Marcel,True,3.0,NaN,SingleFamilyResidence,2.1100,NaN,NaN,2005.0,0,25824.0,4259.0,SW26070221,5.0,Murrieta,NaN,NaN,5.0,2026-04-03,-117.198587,NaN,NaN,2026-04-03,2026-02-20,NaN,NaN,33.532988,1870000.0,CA,NaN,NaN,True,2.0,NaN,Two,Hensley,NaN,NaN,91912.00,1.0,False,3.0,Murrieta,92562,NaN,265.00,91912.0,NaN,25824 Long Acres
18,2950000.0,1156782007,NaN,NaN,Troy,Gray,35.283067,-120.707208,35 Blarney,ResidentialIncome,NaN,2950000.0,1,Kestly Realty Group Inc.,NaN,Kestly Realty Group Inc.,Troy Gray,Jeannie,Pleasant,NaN,NaN,NaN,NaN,NaN,NaN,1156782007,SLO - San Luis Obispo,NaN,San Luis Obispo,ResidentialIncome,Active,NaN,Troy,NaN,0.0,NaN,MixedUse,4.7800,San Luis Obispo(380),NaN,1930.0,1,35.0,NaN,SC26048875,NaN,San Luis Obispo,2025.0,5398.0,NaN,2026-02-12,-120.707208,NaN,NaN,NaN,2026-02-12,NaN,NaN,35.283067,2950000.0,CA,NaN,NaN,NaN,1.0,NaN,One,Gray,NaN,200x1028,208217.00,NaN,False,0.0,NaN,93405,NaN,NaN,208217.0,NaN,35 Blarney
19,1259000.0,1156781511,NaN,NaN,Louis,Pisano,32.755264,-116.908575,2134 Ricard Court,Residential,2248.0,1259000.0,0,Real Broker,NaN,NaN,Louis Pisano,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1156781511,92019 - El Cajon,NaN,San Diego,Residential,ComingSoon,NaN,Louis,True,3.0,NaN,SingleFamilyResidence,0.2300,NaN,NaN,1985.0,0,2134.0,2248.0,PTP2602497,3.0,El Cajon,NaN,NaN,3.0,2026-04-11,-116.908575,NaN,NaN,NaN,2026-02-28,NaN,NaN,32.755264,1259000.0,CA,NaN,NaN,True,2.0,NaN,Two,Pisano,NaN,NaN,0.23,0.0,NaN,3.0,Grossmont Union,92019,NaN,0.00,10018.8,NaN,2134 Ricard Court

In [7]:
df_sold.head(20)

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,DaysOnMarket,ListOfficeName,BuyerOfficeName,CoListOfficeName,ListAgentFullName,CoListAgentFirstName,CoListAgentLastName,BuyerAgentMlsId,BuyerAgentFirstName,BuyerAgentLastName,FireplacesTotal,AssociationFeeFrequency,AboveGradeFinishedArea,ListingKeyNumeric,MLSAreaMajor,TaxAnnualAmount,CountyOrParish,MlsStatus,ElementarySchool,AttachedGarageYN,ParkingTotal,BuilderName,PropertySubType,LotSizeAcres,SubdivisionName,BuyerOfficeAOR,YearBuilt,StreetNumberNumeric,ListingId,BathroomsTotalInteger,City,TaxYear,BuildingAreaTotal,BedroomsTotal,ContractStatusChangeDate,ElementarySchoolDistrict,CoBuyerAgentFirstName,PurchaseContractDate,ListingContractDate,BelowGradeFinishedArea,BusinessType,StateOrProvince,CoveredSpaces,MiddleOrJuniorSchool,FireplaceYN,Stories,HighSchool,Levels,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName
0,HighDesert,HighDesert,NaN,False,NaN,NaN,False,1850000.0,1156290692,2026-02-26,1775000.0,William,Swift,34.538340,-117.250686,18945 Allegheny,ResidentialIncome,NaN,1850000.0,0,Wiest Realty,Wiest Realty,NaN,William Swift,NaN,NaN,HD21501,William,Swift,NaN,NaN,NaN,1156290692,APPV - Apple Valley,NaN,San Bernardino,Closed,NaN,NaN,20.0,NaN,Apartment,0.6818,NaN,HighDesert,1989.0,18945.0,HD26046603,NaN,Apple Valley,NaN,11000.0,NaN,2026-02-26,NaN,NaN,2026-01-13,2026-01-12,NaN,NaN,CA,NaN,NaN,True,NaN,NaN,NaN,NaN,29698.0,NaN,False,20.0,NaN,92307,0.0,29698.0,NaN,CRMLS,CRMLS_CRM
1,ContraCosta,BayEast,NaN,NaN,NaN,NaN,NaN,1580000.0,1155696412,2026-02-19,1580000.0,Kevin,Brown,38.634497,-121.381199,3539 Edison Ave,ResidentialIncome,NaN,1580000.0,385,Better Homes Realty,UNKNOWN,NaN,Kevin Brown,NaN,NaN,CCBE-R00000004,TEST,ID,NaN,NaN,NaN,1155696412,NaN,NaN,Sacramento,Closed,NaN,NaN,20.0,NaN,NaN,0.4289,Other,ContraCosta,1956.0,3539.0,41128127,0.0,Sacramento,NaN,NaN,NaN,2026-02-19,NaN,NaN,2025-10-04,2024-09-14,NaN,NaN,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18682.0,NaN,NaN,NaN,NaN,95821,0.0,18682.0,NaN,CRMLS,CRMLS_CCBE
2,OrangeCounty,OrangeCounty,"Carpet,Tile",False,NaN,NaN,False,1100000.0,1155620121,2026-02-27,1100000.0,Senka,Plese,33.695943,-117.786376,14921 Groveview,Residential,1153.0,1100000.0,0,RE/MAX Connections,RE/MAX Connections,RE/MAX Connections,Senka Plese,Hannah,Song,ocplessen,Senka,Plese,NaN,NaN,NaN,1155620121,EC - El Camino Real,NaN,Orange,Closed,Greentree,True,4.0,NaN,SingleFamilyResidence,0.1148,Willows (WL),OrangeCounty,1971.0,14921.0,OC26061176,2.0,Irvine,NaN,NaN,3.0,2026-02-27,NaN,Hannah,2026-01-27,2026-01-25,NaN,NaN,CA,NaN,Venado,True,1.0,Irvine,One,NaN,5000.0,3.0,False,2.0,Irvine Unified,92604,NaN,5000.0,NaN,CRMLS,CRMLS_CRM
3,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,NaN,NaN,False,999000.0,1155350576,2026-02-27,938000.0,Hosh,Maha,34.187249,-118.464242,6419 Columbus Avenue,Residential,912.0,999000.0,8,EstateX inc.,EstateX inc.,EstateX inc.,Hosh Maha,Sarah,McDonald,CLW-C137047,Hosh,Maha,NaN,NaN,NaN,1155350576,VN - Van Nuys,NaN,Los Angeles,Closed,NaN,NaN,0.0,NaN,SingleFamilyResidence,0.2756,NaN,BeverlyHillsGreaterLa,1933.0,6419.0,26665349,1.0,Van Nuys,NaN,912.0,3.0,2026-02-27,NaN,Claire,2025-11-26,2025-11-18,NaN,NaN,CA,NaN,NaN,True,1.0,NaN,One,107x112,12005.0,NaN,False,NaN,NaN,91411,NaN,12005.0,NaN,CRMLS,CRMLS_CL
4,SanDiego,SanDiego,NaN,NaN,NaN,NaN,NaN,1650000.0,1155221012,2026-02-14,1650000.0,Adam,Cairo,32.636441,-117.075991,259 Alvarado St,CommercialSale,NaN,1650000.0,0,"Starker West, Inc.","Starker West, Inc.","Starker West, Inc.",Adam Cairo,Seth,Watje,SAND-646004,Seth,Watje,NaN,NaN,NaN,1155221012,91910 - Chula Vista,NaN,San Diego,Closed,NaN,NaN,0.0,NaN,MixedUse,0.1573,NaN,SanDiego,NaN,259.0,260006030SD,0.0,Chula Vista,NaN,NaN,NaN,2026-02-14,NaN,NaN,2026-02-14,2026-02-25,NaN,NaN,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6851.0,NaN,NaN,NaN,NaN,91910,0.0,6851.0,NaN,CRMLS,CRMLS_SAND
5,Newport,Newport,NaN,False,NaN,NaN,False,525000.0,1155192177,2026-02-24,525000.0,Dustin,Alamo,38.055464,-122.158783,255 Military W,Residential,2145.0,525000.0,0,"Alamo Pacific Realty, Inc","Alamo Pacific Realty, Inc",NaN,Dustin Alamo,NaN,NaN,NP60281,Dustin,Alamo,NaN,NaN,NaN,1155192177,NaN,NaN,Solano,Closed,NaN,NaN,0.0,NaN,SingleFamilyResidence,0.4300,NaN,Newport,1900.0,255.0,NP26055593,1.0,Benicia,NaN,NaN,4.0,2026-02-24,NaN,NaN,2026-02-08,2026-02-08,NaN,NaN,CA,NaN,NaN,False,2.0,NaN,"Two,ThreeOrMore",NaN,18730.0,4.0,False,0.0,ABC Unified,94510,0.0,18730.0,NaN,CRMLS,CRMLS_CRM
6,Mrmls,SierraNorthValley,NaN,True,NaN,NaN,False,299000.0,1155179209,2026-02-27,240000.0,Marty,Leatherman,39.734906,-121.832084,555 Vallombrosa,Residential,902.0,299000.0,0,Re/Max of Chico,NONMEMBER MRML,NaN,Marty Leatherman,NaN,NaN,nonmember,General,NONMEMBER,NaN,Monthly,NaN,1155179209,NaN,NaN,Butte,Closed,NaN,False,1.0,NaN,Condominium,0.0200,NaN,Mrmls,1973.0,555.0,SN26054377,1.0,Chico,NaN,NaN,2.0,2026-02-27,NaN,NaN,2026-01-29,2026-01-29,NaN,NaN,CA,NaN,NaN,True,1.0,NaN,One,NaN,871.0,2.0,False,1.0,Chico Unified,95926,468.0,871.0,NaN,CRMLS,CRMLS_CRM
7,CitrusValley,WestSanGabrielValley,NaN,False,NaN,NaN,False,905000.0,1155113968,2026-02-17,905000.0,Sarah,Johnson,34.179042,-118.145900,1930 N Marengo,Residential,1214.0,905000.0,0,Real Brokerage Technologies,eXp Realty of Greater Los Angeles,Real Brokerage Technologies,Sarah Johnson,PEGGY,LIM,CV49342,Vivian,Tang,NaN,NaN,NaN,1155113968,645 - Pasadena (NW),NaN,Los Angeles,Closed,NaN,True,2.0,NaN,SingleFamilyResidence,0.1894,NaN,CitrusValley,1976.0,1930.0,WS26031120,2.0,Pasadena,NaN,NaN,4.0,2026-02-17,NaN,Denny,2026-02-17,2026-02-17,NaN,NaN,CA,NaN,NaN,False,1.0,NaN,One,NaN,8251.0,4.0,False,2.0,Pasadena Unified,91103,0.0,8251.0,NaN,CRMLS,CRMLS_CRM
8,BayEast,Oakland,Carpet,NaN,NaN,NaN,False,1210000.0,1155025463,2026-02-27,1210000.0,Michael,Swiderski,37.904778,-122.047183,1066 Hacienda Dr,Residential,1400.0,1210000.0,0,Coldwell Banker Realty,Open Access,NaN,Michael Swiderski,NaN,NaN,BMLS-174568559,Anastasie,Martin,NaN,NaN,NaN,1155025463,NaN,NaN,Contra Costa,Closed,NaN,True,2.0,NaN,SingleFamilyResidence,0.6336,LAKEWOOD,BayEast,1954.0,1066.0,41126804,2.0,Walnut Creek,NaN,NaN,4.0,2026-02-27,NaN,NaN,2026-02-27,2026-02-27,NaN,NaN,CA,NaN,NaN,True,1.0,NaN,One,NaN,27600.0,NaN,False,2.0,NaN,94598,NaN,27600.0,NaN,CRMLS,CRMLS_BMLS
9,Newport,Newport,"Tile,Wood",True,NaN,NaN,False,3150000.0,1154998305,2026-02-24,3150000.0,Casey,O'Connor,33.596168,-117.864925,615 .5 Poppy Avenue,Residential,1400.0,3150000.0,0,Berkshire Hathaway HomeService,Christie's International R.E. Southern California,"Sailhouse Real Estate, Inc.",Casey O'Connor,Pat,Patterson,U40320,Casey,Lesher,NaN,NaN,NaN,1154998305,CS - Corona Del Mar - Spyglass,NaN,Orange,Closed,NaN,True,2.0,NaN,Condominium,0.0813,Corona del Mar North of PCH (CNHW),Newport,2025.0,615.0,NP26053262,4.0,Corona Del Mar,NaN,NaN,3.0,2026-02-24,NaN,NaN,2026-01-30,2025-12-16,NaN,NaN,CA,NaN,NaN,True,NaN,NaN,ThreeOrMore,NaN,3540.0,1.0,True,1.0,Newport Mesa Unified,92625,0.0,3540.0,NaN,CRMLS,CRMLS_CRM
10,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1154943263,2026-02-24,2100000.0,NaN,Strock Team,37.230895,-121.957619,16369 Hilow Road,Residential,1056.0,2100000.0,0,eXp Realty of California Inc,eXp Realty of California Inc,Strock Real Estate,Strock Team,Natalia,Fulga,ML5084906,Bjorn,Berg,NaN,NaN,NaN,1154943263,699 - Not Defined,NaN,Santa Clara,Closed,Other,False,6.0,NaN,SingleFamilyResidence,0.2400,NaN,Mlslistings,1951.0,16369.0,ML82037960,1.0,Los Gatos,NaN,NaN,3.0,2026-02-24,NaN,NaN,2026-02-24,2026-02-24,NaN,NaN,CA,NaN,Raymond J. Fisher,False,NaN,Los Gatos,NaN,NaN,10454.0,NaN,False,2.0,Other,95032,NaN,10454.0,NaN,CRMLS,CRMLS_MLSL
11,NorthSanDiegoCounty,NorthSanDiegoCounty,Laminate,False,NaN,NaN,False,649999.0,1154868125,2026-02-27,700000.0,Jim,Bottrell,32.734123,-117.081553,5304 Nutmeg Street,Residential,1346.0,649999.0,0,eXp Realty Greater Los Angeles,"eXp Realty of Greater Los Angeles, Inc","eXp Realty of Greater Los Angeles, Inc",Jim Bottrell,Brian,Thompson,ND126155,Brian,Thompson,NaN,NaN,NaN,1154868125,92105 - East San Diego,NaN,San Diego,Closed,NaN,True,1.0,NaN,SingleFamilyResidence,0.1263,NaN,NorthSanDiegoCounty,1970.0,5304.0,NDP2602236,2.0,San Diego,NaN,NaN,3.0,2026-02-27,NaN,NaN,2026-02-06,2026-01-26,NaN,NaN,CA,NaN,NaN,False,1.0,NaN,One,NaN,5500.0,NaN,NaN,1.0,San Diego Unified,92105,0.0,5500.0,NaN,CRMLS,CRMLS_CRP
12,NorthSanDiegoCounty,NorthSanDiegoCounty,NaN,True,NaN,NaN,NaN,700000.0,1154785403,2026-02-25,700000.0,Meriah,Druliner,33.194597,-116.791146,0 Mesa Grande Road,Land,NaN,700000.0,0,Chameleon/Red Hawk Realty,Chameleon/Red Hawk Realty,Chameleon/Red Hawk Realty,Meriah Druliner,Donn,Bree,105776,Meriah,Druliner,NaN,NaN,NaN,1154785403,92070 - Santa Ysabel,NaN,San Diego,Closed,NaN,NaN,0.0,NaN,NaN,80.0000,NaN,NorthSanDiegoCounty,NaN,0.0,NDP2602218,0.0,Santa Ysabel,NaN,NaN,NaN,2026-02-25,NaN,NaN,2026-02-01,2026-02-01,NaN,NaN,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,NaN,NaN,NaN,NaN,92070,0.0,3484800.0,NaN,CRMLS,CRMLS_CRP
13,SanDiego,PacificSouthwest,NaN,True,NaN,NaN,False,1191000.0,1154717602,2026-02-27,1191000.0,Esmeralda,Caballero,32.622937,-116.974208,1864 Cobblecreek Street,Residential,2655.0,1191000.0,0,ShoppingSDHouses,Military Mutual,NaN,Esmeralda Caballero,NaN,NaN,SAND-655369,Derek,Barksdale,NaN,Monthly,NaN,1154717602,91913 - Chula Vista,NaN,San Diego,Closed,NaN,True,2.0,NaN,SingleFamilyResidence,0.1000,NaN,SanDiego,2005.0,1864.0,PTP2601759,4.0,Chula Vista,NaN,NaN,6.0,2026-02-27,NaN,NaN,2026-01-30,2026-01-06,NaN,NaN,CA,NaN,NaN,True,1.0,NaN,One,NaN,0.1,NaN,NaN,2.0,Other,91913,135.0,4356.0,NaN,CRMLS,CRMLS_CRP
14,Mrmls,PacificWest,NaN,True,NaN,NaN,True,510000.0,1154531404,2026-02-24,510000.0,Dema,Wasel,37.957510,-121.292474,6395 Embarcadero Drive,Residential,1902.0,510000.0,0,Lifetime Realty Inc,NONMEMBER MRML,NaN,Dema Wasel,NaN,NaN,NONMEMBER,Andrea,Johnson,NaN,Quarterly,NaN,1154531404,NaN,NaN,San Joaquin,Closed,NaN,True,2.0,NaN,SingleFamilyResidence,0.1441,NaN,Mrmls,1980.0,6395.0,PW26049580,2.0,Stockton,NaN,NaN,3.0,2026-02-24,NaN,NaN,2026-01-20,2026-01-15,NaN,NaN,CA,NaN,NaN,True,2.0,NaN,Two,NaN,6277.0,1.0,False,2.0,Lodi Unified,95219,479.0,6277.0,NaN,CRMLS,CRMLS_CRM
15,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,NaN,True,NaN,NaN,False,1500000.0,1154516228,2026-02-20,1500000.0,Bryce,Pennel,34.089607,-118.390129,999 N Doheny Drive 1201,Residential,842.0,1500000.0,0,Douglas Elliman,Douglas Elliman,NaN,Bryce Pennel,NaN,NaN,CLW-C124648,Bryce,Pennel,NaN,Monthly,NaN,1154516228,C10 - West Hollywood Vicinity,NaN,Los Angeles,Closed,NaN,NaN,0.0,NaN,Condominium,0.6809,NaN,BeverlyHillsGreaterLa,1963.0,999.0,26660867,1.0,West Hollywood,NaN,842.0,1.0,2026-02-20,NaN,NaN,2026-02-20,2026-02-20,NaN,NaN,CA,NaN,NaN,False,1.0,NaN,One,NaN,29660.0,NaN,False,NaN,NaN,90069,2000.0,29660.0,NaN,CRMLS,CRMLS_CL
16,NaN,SanDiego,"Carpet,Tile",True,NaN,NaN,False,2425000.0,1154480605,2026-02-20,2330000.0,Tim,Van Damm,32.995804,-117.107782,15094 Verdot Ct,Residential,3030.0,2425000.0,0,Berkshire Hathaway HomeServices California Pro...,Berkshire Hathaway HomeService,Berkshire Hathaway HomeServices California Pro...,Tim Van Damm,Charlie,Cairncross,109783,Shelly,Wu,NaN,Monthly,NaN,1154480605,92127 - Rancho Bernardo,NaN,San Diego,Closed,NaN,True,4.0,NaN,SingleFamilyResidence,0.1671,San Diego,NaN,2016.0,15094.0,260005234SD,3.0,San Diego,NaN,NaN,4.0,2026-02-20,NaN,NaN,2026-02-05,2026-01-23,NaN,NaN,CA,NaN,NaN,False,2.0,NaN,Two,NaN,7281.0,NaN,False,2.0,NaN,92127,227.0,7281.0,NaN,CRMLS,CRMLS_SAND
17,NorthSanDiegoCounty,NorthSanDiegoCounty,NaN,True,NaN,NaN,False,1600000.0,1154376266,2026-02-25,1600000.0,Thomas,Rico,33.130570,-117.178217,680 Westbrook Loop,Residential,3453.0,1600000.0,0,Berkshire Hathaway HomeService,First Team Real Estate,NaN,Thomas Rico,NaN,NaN,100220,Annette,Waite,NaN,Monthly,NaN,1154376266,92078 - San Marcos,NaN,San Diego,Closed,NaN,True,2.0,NaN,Condominium,NaN,NaN,NorthSanDiegoCounty,2022.0,680.0,NDP2602084,5.0,San Marcos,NaN,NaN,5.0,2026-02-25,NaN,NaN,2026-01-25,2026-01-24,NaN,NaN,CA,NaN,NaN,False,2.0,NaN,Two,NaN,NaN,1.0,NaN,2.0,San Marcos Unified,92078,242.0,NaN,NaN,CRMLS,CRMLS_CRP
18,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1154334545,2026-02-27,537000.0,Susan,Gaetano,37.126828,-121.635009,16715 Audrey Drive,Residential,587.0,537000.0,0,Intero Real Estate Services,Intero Real Estate Services,NaN,Susan Gaetano,NaN,NaN,ML493914,Susan,Gaetano,NaN,NaN,NaN,1154334545,699 - Not Defined,NaN,Santa Clara,Closed,NaN,True,1.0,NaN,SingleFamilyResidence,0.0514,NaN,Mlslistings,1990.0,16715.0,ML82037127,1.0,Morgan Hill,NaN,NaN,1.0,2026-02-27,NaN,NaN,2026-02-27,2026-02-27,NaN,NaN,CA,NaN,NaN,False,NaN,NaN,NaN,NaN,2240.0,NaN,False,1.0,Other,95037,276.0,2240.0,NaN,CRMLS,CRMLS_MLSL
19,NaN,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1154334544,2026-02-27,1244000.0,Ella,Barak,37.474870,-122.159837,1208 Henderson Avenue,Residential,1070.0,1244000.0,0,Keller Williams Palo Alto,NaN,NaN,Ella Barak,NaN,NaN,ML1599576,Brian Andrew,Merrion,NaN,NaN,NaN,1154334544,699 - Not Defined,NaN,San Mateo,Closed,NaN,True,1.0,NaN,SingleFamilyResidence,0.1354,NaN,NaN,1948.0,1208.0,ML82037129,1.0,Menlo Park,NaN,NaN,3.0,2026-02-27,NaN,NaN,2026-02-27,2026-02-27,NaN,NaN,CA,NaN,NaN,False,NaN,NaN,NaN,NaN,5900.0,NaN,False,1.0,Other,94025,NaN,5900.0,NaN,CRMLS,CRMLS_MLSL

## 4. Important fields
- Pricing: `OriginalListPrice`, `ClosePrice`
- Dates: `CloseDate`
- Location: `Latitude`, `Longitude`, `PostalCode`, `UnparsedAddress`, `HighSchoolDistrict`
- Property info: `PropertyType`, `GarageSpaces`, `MainLevelBedrooms`, `LotSizeSquareFeet`, `LivingArea`, `DaysOnMarket`

## 5. Structure overview

In [8]:
df_listed.info()
# 30981 x 81

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239785 entries, 0 to 239784
Data columns (total 81 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             238655 non-null  float64
 1   ListingKey                    239785 non-null  int64
 2   CloseDate                     59146 non-null   object
 3   ClosePrice                    54729 non-null   float64
 4   ListAgentFirstName            238646 non-null  object
 5   ListAgentLastName             239774 non-null  object
 6   Latitude                      236894 non-null  float64
 7   Longitude                     236965 non-null  float64
 8   UnparsedAddress               239218 non-null  object
 9   PropertyType                  239785 non-null  object
 10  LivingArea                    207504 non-null  float64
 11  ListPrice                     239095 non-null  float64
 12  DaysOnMarket                  239785 non-null  int64
 13  ListOfficeName                239785 non-null  object
 14  BuyerOfficeName               57260 non-null   object
 15  CoListOfficeName              50644 non-null   object
 16  ListAgentFullName             239627 non-null  object
 17  CoListAgentFirstName          50479 non-null   object
 18  CoListAgentLastName           50605 non-null   object
 19  BuyerAgentMlsId               57645 non-null   object
 20  BuyerAgentFirstName           57649 non-null   object
 21  BuyerAgentLastName            57843 non-null   object
 22  FireplacesTotal               0 non-null       float64
 23  AssociationFeeFrequency       75662 non-null   object
 24  AboveGradeFinishedArea        0 non-null       float64
 25  ListingKeyNumeric             239785 non-null  int64
 26  MLSAreaMajor                  217393 non-null  object
 27  TaxAnnualAmount               1366 non-null    float64
 28  CountyOrParish                239785 non-null  object
 29  PropertyType.1                239785 non-null  object
 30  MlsStatus                     239785 non-null  object
 31  ElementarySchool              24821 non-null   object
 32  ListAgentFirstName.1          238646 non-null  object
 33  AttachedGarageYN              158177 non-null  object
 34  ParkingTotal                  223943 non-null  float64
 35  BuilderName                   8239 non-null    object
 36  PropertySubType               209390 non-null  object
 37  LotSizeAcres                  218753 non-null  float64
 38  SubdivisionName               78895 non-null   object
 39  BuyerOfficeAOR                52858 non-null   object
 40  YearBuilt                     219554 non-null  float64
 41  DaysOnMarket.1                239785 non-null  int64
 42  StreetNumberNumeric           238779 non-null  float64
 43  LivingArea.1                  207504 non-null  float64
 44  ListingId                     239785 non-null  object
 45  BathroomsTotalInteger         217784 non-null  float64
 46  City                          239628 non-null  object
 47  TaxYear                       318 non-null     float64
 48  BuildingAreaTotal             35588 non-null   float64
 49  BedroomsTotal                 208454 non-null  float64
 50  ContractStatusChangeDate      237210 non-null  object
 51  Longitude.1                   236965 non-null  float64
 52  ElementarySchoolDistrict      0 non-null       float64
 53  CoBuyerAgentFirstName         4792 non-null    object
 54  PurchaseContractDate          103446 non-null  object
 55  ListingContractDate           239785 non-null  object
 56  BelowGradeFinishedArea        1234 non-null    float64
 57  BusinessType                  2088 non-null    object
 58  Latitude.1                    236894 non-null  float64
 59  ListPrice.1                   239095 non-null  float64
 60  StateOrProvince               239705 non-null  object
 61  CoveredSpaces                 0 non-null       float64
 62  MiddleOrJuniorSchool          24832 non-null   object
 63  FireplaceYN                   203335 non-null  object
 64  Stories                       179909 non-null  float64
 65  HighSchool                    32349 non-null   object
 66  Levels                        195936 non-null  object
 67  ListAgentLastName.1           239774 non-null  object
 68  CloseDate.1                   59146 non-null   object
 69  LotSizeDimensions             12040 non-null   object
 70  LotSizeArea                   219746 non-null  float64
 71  MainLevelBedrooms             122205 non-null  float64
 72  NewConstructionYN             204668 non-null  object
 73  GarageSpaces                  196382 non-null  float64
 74  HighSchoolDistrict            150603 non-null  object
 75  PostalCode                    239767 non-null  object
 76  BuyerOfficeName.1             57260 non-null   object
 77  AssociationFee                174701 non-null  float64
 78  LotSizeSquareFeet             219416 non-null  float64
 79  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 80  UnparsedAddress.1             239218 non-null  object
dtypes: float64(31), int64(4), object(46)
memory usage: 148.2+ MB

In [9]:
df_sold.info()
# 38161 x 79

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175206 entries, 0 to 175205
Data columns (total 79 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   BuyerAgentAOR                 162361 non-null  object
 1   ListAgentAOR                  175157 non-null  object
 2   Flooring                      100084 non-null  object
 3   ViewYN                        158704 non-null  object
 4   WaterfrontYN                  124 non-null     object
 5   BasementYN                    2695 non-null    object
 6   PoolPrivateYN                 156842 non-null  object
 7   OriginalListPrice             174131 non-null  float64
 8   ListingKey                    175206 non-null  int64
 9   CloseDate                     175206 non-null  object
 10  ClosePrice                    175196 non-null  float64
 11  ListAgentFirstName            174563 non-null  object
 12  ListAgentLastName             175196 non-null  object
 13  Latitude                      173369 non-null  float64
 14  Longitude                     173494 non-null  float64
 15  UnparsedAddress               175021 non-null  object
 16  PropertyType                  175206 non-null  object
 17  LivingArea                    164605 non-null  float64
 18  ListPrice                     175004 non-null  float64
 19  DaysOnMarket                  175206 non-null  int64
 20  ListOfficeName                175206 non-null  object
 21  BuyerOfficeName               173588 non-null  object
 22  CoListOfficeName              35455 non-null   object
 23  ListAgentFullName             175017 non-null  object
 24  CoListAgentFirstName          35333 non-null   object
 25  CoListAgentLastName           35432 non-null   object
 26  BuyerAgentMlsId               174395 non-null  object
 27  BuyerAgentFirstName           174505 non-null  object
 28  BuyerAgentLastName            175037 non-null  object
 29  FireplacesTotal               0 non-null       float64
 30  AssociationFeeFrequency       46296 non-null   object
 31  AboveGradeFinishedArea        0 non-null       float64
 32  ListingKeyNumeric             175206 non-null  int64
 33  MLSAreaMajor                  156462 non-null  object
 34  TaxAnnualAmount               549 non-null     float64
 35  CountyOrParish                175206 non-null  object
 36  MlsStatus                     175206 non-null  object
 37  ElementarySchool              17157 non-null   object
 38  AttachedGarageYN              124322 non-null  object
 39  ParkingTotal                  170737 non-null  float64
 40  BuilderName                   5867 non-null    object
 41  PropertySubType               164103 non-null  object
 42  LotSizeAcres                  159455 non-null  float64
 43  SubdivisionName               65814 non-null   object
 44  BuyerOfficeAOR                161687 non-null  object
 45  YearBuilt                     168169 non-null  float64
 46  StreetNumberNumeric           174869 non-null  float64
 47  ListingId                     175206 non-null  object
 48  BathroomsTotalInteger         168653 non-null  float64
 49  City                          175152 non-null  object
 50  TaxYear                       94 non-null      float64
 51  BuildingAreaTotal             25167 non-null   float64
 52  BedroomsTotal                 165536 non-null  float64
 53  ContractStatusChangeDate      175206 non-null  object
 54  ElementarySchoolDistrict      0 non-null       float64
 55  CoBuyerAgentFirstName         15004 non-null   object
 56  PurchaseContractDate          170688 non-null  object
 57  ListingContractDate           175191 non-null  object
 58  BelowGradeFinishedArea        788 non-null     float64
 59  BusinessType                  354 non-null     object
 60  StateOrProvince               175206 non-null  object
 61  CoveredSpaces                 0 non-null       float64
 62  MiddleOrJuniorSchool          17149 non-null   object
 63  FireplaceYN                   163125 non-null  object
 64  Stories                       143196 non-null  float64
 65  HighSchool                    22262 non-null   object
 66  Levels                        154998 non-null  object
 67  LotSizeDimensions             9804 non-null    object
 68  LotSizeArea                   160283 non-null  float64
 69  MainLevelBedrooms             92717 non-null   float64
 70  NewConstructionYN             154674 non-null  object
 71  GarageSpaces                  151214 non-null  float64
 72  HighSchoolDistrict            113323 non-null  object
 73  PostalCode                    175139 non-null  object
 74  AssociationFee                115260 non-null  float64
 75  LotSizeSquareFeet             160176 non-null  float64
 76  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 77  OriginatingSystemName         175206 non-null  object
 78  OriginatingSystemSubName      175206 non-null  object
dtypes: float64(27), int64(3), object(49)
memory usage: 105.6+ MB

In [10]:
df_listed.describe(include="all").T.head(20)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
OriginalListPrice,238655.0,NaN,NaN,NaN,1112802.904079,6219930.787278,1.0,214000.0,669900.0,1199999.0,819500000.0
ListingKey,239785.0,NaN,NaN,NaN,1153705148.914061,866458.163069,1063377179.0,1153247334.0,1153567794.0,1154144415.0,1156830188.0
CloseDate,59146,120,2026-03-27,3813,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ClosePrice,54729.0,NaN,NaN,NaN,838972.142812,1126198.505029,1.77,4700.0,625000.0,1200000.0,30260000.0
ListAgentFirstName,238646,5785,Michael,3083,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ListAgentLastName,239774,11665,Lee,1427,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Latitude,236894.0,NaN,NaN,NaN,34.47283,1.607657,0.0,33.737049,34.038224,34.296338,41.891615
Longitude,236965.0,NaN,NaN,NaN,-118.288594,4.276344,-124.198589,-118.491974,-118.029157,-117.28381,118.08435
UnparsedAddress,239218,31637,6035 Mesa,81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PropertyType,239785,8,Residential,158229,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LivingArea,207504.0,NaN,NaN,NaN,1938.10018,1580.600527,0.0,1183.0,1619.0,2281.0,94619.0
ListPrice,239095.0,NaN,NaN,NaN,1033655.625916,1998554.771126,1.0,215000.0,660300.0,1199000.0,91350000.0
DaysOnMarket,239785.0,NaN,NaN,NaN,17.255516,15.602872,-17.0,5.0,14.0,28.0,710.0
ListOfficeName,239785,6312,Compass,15525,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BuyerOfficeName,57260,2843,Compass,4954,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CoListOfficeName,50644,1519,Compass,5516,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ListAgentFullName,239627,19767,Mark Mestepey,583,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CoListAgentFirstName,50479,1903,Michael,692,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CoListAgentLastName,50605,3270,Gonzalez,376,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BuyerAgentMlsId,57645,8157,NONMEMBER,909,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_sold.describe(include="all").T.head(20)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
BuyerAgentAOR,162361,56,BeverlyHillsGreaterLa,16965,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ListAgentAOR,175157,52,OrangeCounty,19048,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Flooring,100084,142,Wood,12849,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ViewYN,158704,2,True,95468,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WaterfrontYN,124,1,True,124,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BasementYN,2695,1,True,2695,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PoolPrivateYN,156842,2,False,140389,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OriginalListPrice,174131.0,NaN,NaN,NaN,1016180.829577,11124223.05062,1.0,4950.0,545000.0,999000.0,589888000.0
ListingKey,175206.0,NaN,NaN,NaN,1148020284.309316,11144243.215271,425835813.0,1149469766.0,1151205672.0,1151960635.0,1156290692.0
CloseDate,175206,28,2026-02-27,19075,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ClosePrice,175196.0,NaN,NaN,NaN,767378.650353,1221884.508864,0.0,4950.0,535000.0,1010000.0,40000000.0
ListAgentFirstName,174563,4381,David,2110,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ListAgentLastName,175196,8539,Lee,1158,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Latitude,173369.0,NaN,NaN,NaN,34.486212,1.588097,0.0,33.71385,34.029052,34.243687,41.72184
Longitude,173494.0,NaN,NaN,NaN,-118.434259,3.997382,-123.809284,-118.513217,-118.06732,-117.36311,118.14003
UnparsedAddress,175021,18942,2101 Ocean Avenue 14,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PropertyType,175206,8,Residential,102675,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LivingArea,164605.0,NaN,NaN,NaN,1779.61588,1678.240248,0.0,1139.0,1542.0,2109.0,94619.0
ListPrice,175004.0,NaN,NaN,NaN,767451.671636,1261652.219151,2.0,4900.0,539900.0,999000.0,49500000.0
DaysOnMarket,175206.0,NaN,NaN,NaN,33.479898,59.36284,-14.0,6.0,12.0,35.0,2094.0

In [12]:
df_listed.dtypes

OriginalListPrice               float64
ListingKey                        int64
CloseDate                        object
ClosePrice                      float64
ListAgentFirstName               object
                                 ...
BuyerOfficeName.1                object
AssociationFee                  float64
LotSizeSquareFeet               float64
MiddleOrJuniorSchoolDistrict    float64
UnparsedAddress.1                object
Length: 81, dtype: object

In [13]:
df_sold.dtypes

BuyerAgentAOR                    object
ListAgentAOR                     object
Flooring                         object
ViewYN                           object
WaterfrontYN                     object
                                 ...
AssociationFee                  float64
LotSizeSquareFeet               float64
MiddleOrJuniorSchoolDistrict    float64
OriginatingSystemName            object
OriginatingSystemSubName         object
Length: 79, dtype: object

## 6. Missing values

In [14]:
df_listed.isnull().sum().sort_values(ascending=False).head(15)

FireplacesTotal                 239785
CoveredSpaces                   239785
MiddleOrJuniorSchoolDistrict    239785
ElementarySchoolDistrict        239785
AboveGradeFinishedArea          239785
TaxYear                         239467
BelowGradeFinishedArea          238551
TaxAnnualAmount                 238419
BusinessType                    237697
CoBuyerAgentFirstName           234993
BuilderName                     231546
LotSizeDimensions               227745
ElementarySchool                214964
MiddleOrJuniorSchool            214953
HighSchool                      207436
dtype: int64

In [15]:
df_sold.isnull().sum().sort_values(ascending=False).head(15)

CoveredSpaces                   175206
MiddleOrJuniorSchoolDistrict    175206
ElementarySchoolDistrict        175206
AboveGradeFinishedArea          175206
FireplacesTotal                 175206
TaxYear                         175112
WaterfrontYN                    175082
BusinessType                    174852
TaxAnnualAmount                 174657
BelowGradeFinishedArea          174418
BasementYN                      172511
BuilderName                     169339
LotSizeDimensions               165402
CoBuyerAgentFirstName           160202
MiddleOrJuniorSchool            158057
dtype: int64

In [16]:
df_listed.isnull().mean().sort_values(ascending=False).head(15)

FireplacesTotal                 1.000000
CoveredSpaces                   1.000000
MiddleOrJuniorSchoolDistrict    1.000000
ElementarySchoolDistrict        1.000000
AboveGradeFinishedArea          1.000000
TaxYear                         0.998674
BelowGradeFinishedArea          0.994854
TaxAnnualAmount                 0.994303
BusinessType                    0.991292
CoBuyerAgentFirstName           0.980015
BuilderName                     0.965640
LotSizeDimensions               0.949788
ElementarySchool                0.896486
MiddleOrJuniorSchool            0.896441
HighSchool                      0.865092
dtype: float64

In [17]:
df_sold.isnull().mean().sort_values(ascending=False).head(15)

CoveredSpaces                   1.000000
MiddleOrJuniorSchoolDistrict    1.000000
ElementarySchoolDistrict        1.000000
AboveGradeFinishedArea          1.000000
FireplacesTotal                 1.000000
TaxYear                         0.999463
WaterfrontYN                    0.999292
BusinessType                    0.997980
TaxAnnualAmount                 0.996867
BelowGradeFinishedArea          0.995502
BasementYN                      0.984618
BuilderName                     0.966514
LotSizeDimensions               0.944043
CoBuyerAgentFirstName           0.914364
MiddleOrJuniorSchool            0.902121
dtype: float64

## 7. Property type counts

This shows how much of the data is Residential versus lease, land, commercial, and other categories.

In [18]:
df_listed["PropertyType"].value_counts(dropna=False)

PropertyType
Residential            158229
ResidentialLease        40462
Land                    16405
ResidentialIncome       10342
ManufacturedInPark       7381
CommercialSale           3690
CommercialLease          2373
BusinessOpportunity       903
Name: count, dtype: int64

In [19]:
df_sold["PropertyType"].value_counts(dropna=False)

PropertyType
Residential            102675
ResidentialLease        58973
Land                     4950
ResidentialIncome        3610
ManufacturedInPark       3195
CommercialSale            921
CommercialLease           819
BusinessOpportunity        63
Name: count, dtype: int64

## 8. Columns to keep

In [20]:
important_cols = [
    "CloseDate",
    "ClosePrice",
    "OriginalListPrice",
    "PropertyType",
    "LivingArea",
    "LotSizeSquareFeet",
    "PostalCode",
    "DaysOnMarket"
]

important_cols

['CloseDate',
 'ClosePrice',
 'OriginalListPrice',
 'PropertyType',
 'LivingArea',
 'LotSizeSquareFeet',
 'PostalCode',
 'DaysOnMarket']

## 9. Column dropping(any above 90% except for important_cols)

In [21]:
threshold = 0.9

missing_listed = df_listed.isnull().mean()

listed_cols_to_drop = [
    col for col in df_listed.columns
    if (missing_listed[col] > threshold) and (col not in important_cols)
]

print("Number of listed columns to drop:", len(listed_cols_to_drop))
listed_cols_to_drop[:20]

Number of listed columns to drop: 12

['FireplacesTotal',
 'AboveGradeFinishedArea',
 'TaxAnnualAmount',
 'BuilderName',
 'TaxYear',
 'ElementarySchoolDistrict',
 'CoBuyerAgentFirstName',
 'BelowGradeFinishedArea',
 'BusinessType',
 'CoveredSpaces',
 'LotSizeDimensions',
 'MiddleOrJuniorSchoolDistrict']

In [22]:
df_listed_clean = df_listed.drop(columns=listed_cols_to_drop)

print("Original listed shape:", df_listed.shape)
print("Clean listed shape:", df_listed_clean.shape)

Original listed shape: (239785, 81)
Clean listed shape: (239785, 69)

In [23]:
missing_sold = df_sold.isnull().mean()

sold_cols_to_drop = [
    col for col in df_sold.columns
    if (missing_sold[col] > threshold) and (col not in important_cols)
]

print("Number of sold columns to drop:", len(sold_cols_to_drop))
sold_cols_to_drop[:20]

Number of sold columns to drop: 16

['WaterfrontYN',
 'BasementYN',
 'FireplacesTotal',
 'AboveGradeFinishedArea',
 'TaxAnnualAmount',
 'ElementarySchool',
 'BuilderName',
 'TaxYear',
 'ElementarySchoolDistrict',
 'CoBuyerAgentFirstName',
 'BelowGradeFinishedArea',
 'BusinessType',
 'CoveredSpaces',
 'MiddleOrJuniorSchool',
 'LotSizeDimensions',
 'MiddleOrJuniorSchoolDistrict']

In [24]:
df_sold_clean = df_sold.drop(columns=sold_cols_to_drop)

print("Original sold shape:", df_sold.shape)
print("Clean sold shape:", df_sold_clean.shape)

Original sold shape: (175206, 79)
Clean sold shape: (175206, 63)

## 10. Checking cleaned datasets

In [25]:
df_listed_clean.head()

,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,DaysOnMarket,ListOfficeName,BuyerOfficeName,CoListOfficeName,ListAgentFullName,CoListAgentFirstName,CoListAgentLastName,BuyerAgentMlsId,BuyerAgentFirstName,BuyerAgentLastName,AssociationFeeFrequency,ListingKeyNumeric,MLSAreaMajor,CountyOrParish,PropertyType.1,MlsStatus,ElementarySchool,ListAgentFirstName.1,AttachedGarageYN,ParkingTotal,PropertySubType,LotSizeAcres,SubdivisionName,BuyerOfficeAOR,YearBuilt,DaysOnMarket.1,StreetNumberNumeric,LivingArea.1,ListingId,BathroomsTotalInteger,City,BuildingAreaTotal,BedroomsTotal,ContractStatusChangeDate,Longitude.1,PurchaseContractDate,ListingContractDate,Latitude.1,ListPrice.1,StateOrProvince,MiddleOrJuniorSchool,FireplaceYN,Stories,HighSchool,Levels,ListAgentLastName.1,CloseDate.1,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,UnparsedAddress.1
0,1498000.0,1156830188,NaN,NaN,Susan,Vega,33.630408,-117.694901,22871 Willard,Residential,2403.0,1498000.0,0,Realty One Group West,NaN,NaN,Susan Vega,NaN,NaN,NaN,NaN,NaN,Monthly,1156830188,LS - Lake Forest South,Orange,Residential,ComingSoon,NaN,Susan,True,2.0,SingleFamilyResidence,0.2184,NaN,NaN,1965.0,0,22871.0,2403.0,OC26065585,3.0,Lake Forest,NaN,4.0,2026-04-09,-117.694901,NaN,2026-02-25,33.630408,1498000.0,CA,NaN,True,1.0,NaN,One,Vega,NaN,9513.0,4.0,False,2.0,Saddleback Valley Unified,92630,NaN,132.0,9513.0,22871 Willard
1,1068000.0,1156828950,NaN,NaN,glenn,hammerburg,36.697911,-119.549810,1240 J Street,ResidentialIncome,NaN,1068000.0,0,Realty Fresno,NaN,NaN,glenn hammerburg,NaN,NaN,NaN,NaN,NaN,NaN,1156828950,FSNO - Fresno,Fresno,ResidentialIncome,Active,NaN,glenn,NaN,7.0,Apartment,0.3300,Not Applicable,NaN,1930.0,0,1240.0,NaN,V1-35600,0.0,Sanger,5242.0,NaN,2026-02-03,-119.549810,NaN,2026-02-03,36.697911,1068000.0,CA,NaN,False,NaN,NaN,NaN,hammerburg,NaN,14374.0,NaN,True,0.0,NaN,93657,NaN,0.0,14374.0,1240 J Street
2,1980000.0,1156824533,NaN,NaN,Affie,Setoodeh,33.980656,-117.522061,5930 Etiwanda,CommercialSale,NaN,1980000.0,0,CENTURY 21 Affiliated,NaN,NaN,Affie Setoodeh,NaN,NaN,NaN,NaN,NaN,NaN,1156824533,251 - Jurupa Valley,Riverside,CommercialSale,Active,NaN,Affie,NaN,10.0,MixedUse,2.6600,NaN,NaN,1952.0,0,5930.0,NaN,OC26072856,NaN,Jurupa Valley,3230.0,NaN,2026-02-26,-117.522061,NaN,2026-02-26,33.980656,1980000.0,CA,NaN,NaN,NaN,NaN,NaN,Setoodeh,NaN,115870.0,NaN,NaN,NaN,NaN,91752,NaN,NaN,115870.0,5930 Etiwanda
3,499000.0,1156818465,NaN,NaN,Keersten,Milson,33.976312,-116.522054,65352 Rolling Hills,Residential,2089.0,499000.0,0,Capitis Real Estate,NaN,NaN,Keersten Milson,NaN,NaN,NaN,NaN,NaN,NaN,1156818465,341 - Mission Lakes,Riverside,Residential,Active,NaN,Keersten,True,2.0,SingleFamilyResidence,0.2100,Mission Lakes (34101),NaN,2020.0,0,65352.0,2089.0,JT26072467,3.0,Desert Hot Springs,NaN,4.0,2026-02-03,-116.522054,NaN,2026-02-03,33.976312,499000.0,CA,NaN,False,1.0,NaN,One,Milson,NaN,9148.0,4.0,False,2.0,Palm Springs Unified,92240,NaN,0.0,9148.0,65352 Rolling Hills
4,5500.0,1156816107,NaN,NaN,Nicholas,Cosfol,34.131821,-118.340211,3121 Lake Hollywood Drive,ResidentialLease,1357.0,5500.0,0,Property Masters Realty,NaN,NaN,Nicholas Cosfol,NaN,NaN,NaN,NaN,NaN,NaN,1156816107,C30 - Hollywood Hills East,Los Angeles,ResidentialLease,Active,NaN,Nicholas,True,1.0,SingleFamilyResidence,0.1732,Not Applicable,NaN,1948.0,0,3121.0,1357.0,P1-26556,2.0,Los Angeles,NaN,2.0,2026-02-17,-118.340211,NaN,2026-02-17,34.131821,5500.0,CA,NaN,True,1.0,NaN,One,Cosfol,NaN,7543.0,NaN,NaN,1.0,NaN,90068,NaN,0.0,7543.0,3121 Lake Hollywood Drive

In [26]:
df_sold_clean.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,PoolPrivateYN,OriginalListPrice,ListingKey,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,DaysOnMarket,ListOfficeName,BuyerOfficeName,CoListOfficeName,ListAgentFullName,CoListAgentFirstName,CoListAgentLastName,BuyerAgentMlsId,BuyerAgentFirstName,BuyerAgentLastName,AssociationFeeFrequency,ListingKeyNumeric,MLSAreaMajor,CountyOrParish,MlsStatus,AttachedGarageYN,ParkingTotal,PropertySubType,LotSizeAcres,SubdivisionName,BuyerOfficeAOR,YearBuilt,StreetNumberNumeric,ListingId,BathroomsTotalInteger,City,BuildingAreaTotal,BedroomsTotal,ContractStatusChangeDate,PurchaseContractDate,ListingContractDate,StateOrProvince,FireplaceYN,Stories,HighSchool,Levels,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,OriginatingSystemName,OriginatingSystemSubName
0,HighDesert,HighDesert,NaN,False,False,1850000.0,1156290692,2026-02-26,1775000.0,William,Swift,34.538340,-117.250686,18945 Allegheny,ResidentialIncome,NaN,1850000.0,0,Wiest Realty,Wiest Realty,NaN,William Swift,NaN,NaN,HD21501,William,Swift,NaN,1156290692,APPV - Apple Valley,San Bernardino,Closed,NaN,20.0,Apartment,0.6818,NaN,HighDesert,1989.0,18945.0,HD26046603,NaN,Apple Valley,11000.0,NaN,2026-02-26,2026-01-13,2026-01-12,CA,True,NaN,NaN,NaN,29698.0,NaN,False,20.0,NaN,92307,0.0,29698.0,CRMLS,CRMLS_CRM
1,ContraCosta,BayEast,NaN,NaN,NaN,1580000.0,1155696412,2026-02-19,1580000.0,Kevin,Brown,38.634497,-121.381199,3539 Edison Ave,ResidentialIncome,NaN,1580000.0,385,Better Homes Realty,UNKNOWN,NaN,Kevin Brown,NaN,NaN,CCBE-R00000004,TEST,ID,NaN,1155696412,NaN,Sacramento,Closed,NaN,20.0,NaN,0.4289,Other,ContraCosta,1956.0,3539.0,41128127,0.0,Sacramento,NaN,NaN,2026-02-19,2025-10-04,2024-09-14,CA,NaN,NaN,NaN,NaN,18682.0,NaN,NaN,NaN,NaN,95821,0.0,18682.0,CRMLS,CRMLS_CCBE
2,OrangeCounty,OrangeCounty,"Carpet,Tile",False,False,1100000.0,1155620121,2026-02-27,1100000.0,Senka,Plese,33.695943,-117.786376,14921 Groveview,Residential,1153.0,1100000.0,0,RE/MAX Connections,RE/MAX Connections,RE/MAX Connections,Senka Plese,Hannah,Song,ocplessen,Senka,Plese,NaN,1155620121,EC - El Camino Real,Orange,Closed,True,4.0,SingleFamilyResidence,0.1148,Willows (WL),OrangeCounty,1971.0,14921.0,OC26061176,2.0,Irvine,NaN,3.0,2026-02-27,2026-01-27,2026-01-25,CA,True,1.0,Irvine,One,5000.0,3.0,False,2.0,Irvine Unified,92604,NaN,5000.0,CRMLS,CRMLS_CRM
3,BeverlyHillsGreaterLa,BeverlyHillsGreaterLa,Wood,False,False,999000.0,1155350576,2026-02-27,938000.0,Hosh,Maha,34.187249,-118.464242,6419 Columbus Avenue,Residential,912.0,999000.0,8,EstateX inc.,EstateX inc.,EstateX inc.,Hosh Maha,Sarah,McDonald,CLW-C137047,Hosh,Maha,NaN,1155350576,VN - Van Nuys,Los Angeles,Closed,NaN,0.0,SingleFamilyResidence,0.2756,NaN,BeverlyHillsGreaterLa,1933.0,6419.0,26665349,1.0,Van Nuys,912.0,3.0,2026-02-27,2025-11-26,2025-11-18,CA,True,1.0,NaN,One,12005.0,NaN,False,NaN,NaN,91411,NaN,12005.0,CRMLS,CRMLS_CL
4,SanDiego,SanDiego,NaN,NaN,NaN,1650000.0,1155221012,2026-02-14,1650000.0,Adam,Cairo,32.636441,-117.075991,259 Alvarado St,CommercialSale,NaN,1650000.0,0,"Starker West, Inc.","Starker West, Inc.","Starker West, Inc.",Adam Cairo,Seth,Watje,SAND-646004,Seth,Watje,NaN,1155221012,91910 - Chula Vista,San Diego,Closed,NaN,0.0,MixedUse,0.1573,NaN,SanDiego,NaN,259.0,260006030SD,0.0,Chula Vista,NaN,NaN,2026-02-14,2026-02-14,2026-02-25,CA,NaN,NaN,NaN,NaN,6851.0,NaN,NaN,NaN,NaN,91910,0.0,6851.0,CRMLS,CRMLS_SAND

In [27]:
df_listed_clean.columns.tolist()

['OriginalListPrice',
 'ListingKey',
 'CloseDate',
 'ClosePrice',
 'ListAgentFirstName',
 'ListAgentLastName',
 'Latitude',
 'Longitude',
 'UnparsedAddress',
 'PropertyType',
 'LivingArea',
 'ListPrice',
 'DaysOnMarket',
 'ListOfficeName',
 'BuyerOfficeName',
 'CoListOfficeName',
 'ListAgentFullName',
 'CoListAgentFirstName',
 'CoListAgentLastName',
 'BuyerAgentMlsId',
 'BuyerAgentFirstName',
 'BuyerAgentLastName',
 'AssociationFeeFrequency',
 'ListingKeyNumeric',
 'MLSAreaMajor',
 'CountyOrParish',
 'PropertyType.1',
 'MlsStatus',
 'ElementarySchool',
 'ListAgentFirstName.1',
 'AttachedGarageYN',
 'ParkingTotal',
 'PropertySubType',
 'LotSizeAcres',
 'SubdivisionName',
 'BuyerOfficeAOR',
 'YearBuilt',
 'DaysOnMarket.1',
 'StreetNumberNumeric',
 'LivingArea.1',
 'ListingId',
 'BathroomsTotalInteger',
 'City',
 'BuildingAreaTotal',
 'BedroomsTotal',
 'ContractStatusChangeDate',
 'Longitude.1',
 'PurchaseContractDate',
 'ListingContractDate',
 'Latitude.1',
 'ListPrice.1',
 'StateOrProvince',
 'MiddleOrJuniorSchool',
 'FireplaceYN',
 'Stories',
 'HighSchool',
 'Levels',
 'ListAgentLastName.1',
 'CloseDate.1',
 'LotSizeArea',
 'MainLevelBedrooms',
 'NewConstructionYN',
 'GarageSpaces',
 'HighSchoolDistrict',
 'PostalCode',
 'BuyerOfficeName.1',
 'AssociationFee',
 'LotSizeSquareFeet',
 'UnparsedAddress.1']

In [28]:
df_sold_clean.columns.tolist()

['BuyerAgentAOR',
 'ListAgentAOR',
 'Flooring',
 'ViewYN',
 'PoolPrivateYN',
 'OriginalListPrice',
 'ListingKey',
 'CloseDate',
 'ClosePrice',
 'ListAgentFirstName',
 'ListAgentLastName',
 'Latitude',
 'Longitude',
 'UnparsedAddress',
 'PropertyType',
 'LivingArea',
 'ListPrice',
 'DaysOnMarket',
 'ListOfficeName',
 'BuyerOfficeName',
 'CoListOfficeName',
 'ListAgentFullName',
 'CoListAgentFirstName',
 'CoListAgentLastName',
 'BuyerAgentMlsId',
 'BuyerAgentFirstName',
 'BuyerAgentLastName',
 'AssociationFeeFrequency',
 'ListingKeyNumeric',
 'MLSAreaMajor',
 'CountyOrParish',
 'MlsStatus',
 'AttachedGarageYN',
 'ParkingTotal',
 'PropertySubType',
 'LotSizeAcres',
 'SubdivisionName',
 'BuyerOfficeAOR',
 'YearBuilt',
 'StreetNumberNumeric',
 'ListingId',
 'BathroomsTotalInteger',
 'City',
 'BuildingAreaTotal',
 'BedroomsTotal',
 'ContractStatusChangeDate',
 'PurchaseContractDate',
 'ListingContractDate',
 'StateOrProvince',
 'FireplaceYN',
 'Stories',
 'HighSchool',
 'Levels',
 'LotSizeArea',
 'MainLevelBedrooms',
 'NewConstructionYN',
 'GarageSpaces',
 'HighSchoolDistrict',
 'PostalCode',
 'AssociationFee',
 'LotSizeSquareFeet',
 'OriginatingSystemName',
 'OriginatingSystemSubName']

## 11. Data Cleaning and Preparation
- converting date columns to datetime
- converting numeric columns to numeric types
- handling invalid values
- creating date consistency flags
- creating geographic data quality flags
- summarizing before/after row counts and data types
- saving cleaned analysis-ready CSV files

In [29]:
# Make working copies so the earlier cleaned dataframes stay unchanged
listed_wk45 = df_listed_clean.copy()
sold_wk45 = df_sold_clean.copy()

listed_original_rows = len(listed_wk45)
sold_original_rows = len(sold_wk45)

print("Starting listed rows:", listed_original_rows)
print("Starting sold rows:", sold_original_rows)

Starting listed rows: 239785
Starting sold rows: 175206

In [30]:
def convert_existing_columns_to_datetime(df, columns):
    for col in columns:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors="coerce")
    return df

def convert_existing_columns_to_numeric(df, columns):
    for col in columns:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")
    return df

date_cols = [
    "CloseDate",
    "PurchaseContractDate",
    "ListingContractDate",
    "ContractStatusChangeDate"
]

numeric_cols = [
    "ClosePrice",
    "ListPrice",
    "OriginalListPrice",
    "LivingArea",
    "LotSizeSquareFeet",
    "DaysOnMarket",
    "BedroomsTotal",
    "BathroomsTotalInteger",
    "Latitude",
    "Longitude"
]

listed_wk45 = convert_existing_columns_to_datetime(listed_wk45, date_cols)
sold_wk45 = convert_existing_columns_to_datetime(sold_wk45, date_cols)

listed_wk45 = convert_existing_columns_to_numeric(listed_wk45, numeric_cols)
sold_wk45 = convert_existing_columns_to_numeric(sold_wk45, numeric_cols)

print("Date and numeric conversions completed.")

Date and numeric conversions completed.

In [31]:
# Remove or filter clearly invalid numeric values required by the handbook.
# We only apply a rule if that column exists in the dataframe.

def apply_invalid_value_filters(df):
    mask = pd.Series(True, index=df.index)

    if "ClosePrice" in df.columns:
        mask &= df["ClosePrice"] > 0
    if "LivingArea" in df.columns:
        mask &= df["LivingArea"] > 0
    if "DaysOnMarket" in df.columns:
        mask &= df["DaysOnMarket"] >= 0
    if "BedroomsTotal" in df.columns:
        mask &= df["BedroomsTotal"].isna() | (df["BedroomsTotal"] >= 0)
    if "BathroomsTotalInteger" in df.columns:
        mask &= df["BathroomsTotalInteger"].isna() | (df["BathroomsTotalInteger"] >= 0)

    return df.loc[mask].copy()

listed_wk45 = apply_invalid_value_filters(listed_wk45)
sold_wk45 = apply_invalid_value_filters(sold_wk45)

print("Listed rows after invalid-value filtering:", len(listed_wk45))
print("Sold rows after invalid-value filtering:", len(sold_wk45))

Listed rows after invalid-value filtering: 52318
Sold rows after invalid-value filtering: 164406

In [32]:
# Create date consistency flags.
# These help identify records where the transaction timeline looks logically incorrect.

def add_date_flags(df):
    if "ListingContractDate" in df.columns and "CloseDate" in df.columns:
        df["listing_after_close_flag"] = df["ListingContractDate"] > df["CloseDate"]
    else:
        df["listing_after_close_flag"] = False

    if "PurchaseContractDate" in df.columns and "CloseDate" in df.columns:
        df["purchase_after_close_flag"] = df["PurchaseContractDate"] > df["CloseDate"]
    else:
        df["purchase_after_close_flag"] = False

    if "ListingContractDate" in df.columns and "PurchaseContractDate" in df.columns:
        df["negative_timeline_flag"] = df["PurchaseContractDate"] < df["ListingContractDate"]
    else:
        df["negative_timeline_flag"] = False

    return df

listed_wk45 = add_date_flags(listed_wk45)
sold_wk45 = add_date_flags(sold_wk45)

listed_wk45[[
    "listing_after_close_flag",
    "purchase_after_close_flag",
    "negative_timeline_flag"
]].sum()

listing_after_close_flag     23
purchase_after_close_flag    12
negative_timeline_flag       76
dtype: int64

In [33]:
# Create geographic data quality flags.

def add_geo_flags(df):
    if "Latitude" in df.columns and "Longitude" in df.columns:
        df["missing_coords_flag"] = df["Latitude"].isna() | df["Longitude"].isna()
        df["zero_coords_flag"] = (df["Latitude"] == 0) | (df["Longitude"] == 0)
        df["invalid_longitude_flag"] = df["Longitude"] > 0

        # Broad plausibility bounds for California-area coordinates
        df["out_of_bounds_flag"] = (
            (df["Latitude"] < 30) | (df["Latitude"] > 45) |
            (df["Longitude"] < -130) | (df["Longitude"] > -110)
        )
    else:
        df["missing_coords_flag"] = False
        df["zero_coords_flag"] = False
        df["invalid_longitude_flag"] = False
        df["out_of_bounds_flag"] = False

    return df

listed_wk45 = add_geo_flags(listed_wk45)
sold_wk45 = add_geo_flags(sold_wk45)

sold_wk45[[
    "missing_coords_flag",
    "zero_coords_flag",
    "invalid_longitude_flag",
    "out_of_bounds_flag"
]].sum()

missing_coords_flag       1312
zero_coords_flag            20
invalid_longitude_flag      36
out_of_bounds_flag          56
dtype: int64

In [34]:
# Fill a few useful numeric fields with medians when they exist.

def fill_selected_numeric_nulls(df, columns):
    for col in columns:
        if col in df.columns and df[col].isnull().any():
            df[col] = df[col].fillna(df[col].median())
    return df

fill_cols = ["BedroomsTotal", "BathroomsTotalInteger", "DaysOnMarket"]

listed_wk45 = fill_selected_numeric_nulls(listed_wk45, fill_cols)
sold_wk45 = fill_selected_numeric_nulls(sold_wk45, fill_cols)

print("Selected missing numeric values filled with medians where applicable.")

Selected missing numeric values filled with medians where applicable.

In [35]:
# Before/after row counts and type confirmations

print("LISTED before cleaning:", listed_original_rows)
print("LISTED after cleaning:", len(listed_wk45))
print("SOLD before cleaning:", sold_original_rows)
print("SOLD after cleaning:", len(sold_wk45))

print("\nListed dtypes:")
print(listed_wk45.dtypes)

print("\nSold dtypes:")
print(sold_wk45.dtypes)

LISTED before cleaning: 239785
LISTED after cleaning: 52318
SOLD before cleaning: 175206
SOLD after cleaning: 164406

Listed dtypes:
OriginalListPrice                float64
ListingKey                         int64
CloseDate                 datetime64[ns]
ClosePrice                       float64
ListAgentFirstName                object
                               ...
negative_timeline_flag              bool
missing_coords_flag                 bool
zero_coords_flag                    bool
invalid_longitude_flag              bool
out_of_bounds_flag                  bool
Length: 76, dtype: object

Sold dtypes:
BuyerAgentAOR             object
ListAgentAOR              object
Flooring                  object
ViewYN                    object
PoolPrivateYN             object
                           ...
negative_timeline_flag      bool
missing_coords_flag         bool
zero_coords_flag            bool
invalid_longitude_flag      bool
out_of_bounds_flag          bool
Length: 70, dtype: object

In [36]:
# Date consistency and geographic quality summaries

print("LISTED date flag counts")
print(listed_wk45[[
    "listing_after_close_flag",
    "purchase_after_close_flag",
    "negative_timeline_flag"
]].sum())

print("\nLISTED geographic flag counts")
print(listed_wk45[[
    "missing_coords_flag",
    "zero_coords_flag",
    "invalid_longitude_flag",
    "out_of_bounds_flag"
]].sum())

print("\nSOLD date flag counts")
print(sold_wk45[[
    "listing_after_close_flag",
    "purchase_after_close_flag",
    "negative_timeline_flag"
]].sum())

print("\nSOLD geographic flag counts")
print(sold_wk45[[
    "missing_coords_flag",
    "zero_coords_flag",
    "invalid_longitude_flag",
    "out_of_bounds_flag"
]].sum())

LISTED date flag counts
listing_after_close_flag     23
purchase_after_close_flag    12
negative_timeline_flag       76
dtype: int64

LISTED geographic flag counts
missing_coords_flag       488
zero_coords_flag           11
invalid_longitude_flag      0
out_of_bounds_flag         11
dtype: int64

SOLD date flag counts
listing_after_close_flag      78
purchase_after_close_flag     13
negative_timeline_flag       213
dtype: int64

SOLD geographic flag counts
missing_coords_flag       1312
zero_coords_flag            20
invalid_longitude_flag      36
out_of_bounds_flag          56
dtype: int64

In [37]:
# Save final cleaned datasets

listed_wk45.to_csv("cleaned_listed_week45.csv", index=False)
sold_wk45.to_csv("cleaned_sold_week45.csv", index=False)

print("Saved cleaned_listed_week45.csv")
print("Saved cleaned_sold_week45.csv")

Saved cleaned_listed_week45.csv
Saved cleaned_sold_week45.csv

## Cleaning + Validation

In [38]:
# Save original row counts
original_sold_rows = len(df_sold_clean)
original_listed_rows = len(df_listed_clean)

print("Original sold rows:", original_sold_rows)
print("Original listed rows:", original_listed_rows)

Original sold rows: 175206
Original listed rows: 239785

In [39]:
# 90% missing value threshold
# Checking if we dropped the columns correctly earlier
missing_pct_sold = df_sold_clean.isnull().mean()
missing_pct_listed = df_listed_clean.isnull().mean()

sold_drop_cols = missing_pct_sold[missing_pct_sold > 0.9].index
listed_drop_cols = missing_pct_listed[missing_pct_listed > 0.9].index

df_sold_clean = df_sold_clean.drop(columns=sold_drop_cols)
df_listed_clean = df_listed_clean.drop(columns=listed_drop_cols)

print("Dropped sold cols:", list(sold_drop_cols))
print("Dropped listed cols:", list(listed_drop_cols))

Dropped sold cols: []
Dropped listed cols: []

In [40]:
# Convert date columns
date_cols = ['CloseDate','PurchaseContractDate','ListingContractDate','ContractStatusChangeDate']

for col in date_cols:
    if col in df_sold_clean.columns:
        df_sold_clean[col] = pd.to_datetime(df_sold_clean[col], errors='coerce')
    if col in df_listed_clean.columns:
        df_listed_clean[col] = pd.to_datetime(df_listed_clean[col], errors='coerce')

In [41]:
# Numeric cleaning
numeric_cols = ['ClosePrice','LivingArea','DaysOnMarket','BedroomsTotal','BathroomsTotalInteger']

for col in numeric_cols:
    if col in df_sold_clean.columns:
        df_sold_clean[col] = pd.to_numeric(df_sold_clean[col], errors='coerce')
    if col in df_listed_clean.columns:
        df_listed_clean[col] = pd.to_numeric(df_listed_clean[col], errors='coerce')

In [42]:
# Remove invalid values
df_sold_clean = df_sold_clean[
    (df_sold_clean['ClosePrice'] > 0) &
    (df_sold_clean['LivingArea'] > 0) &
    (df_sold_clean['DaysOnMarket'] >= 0)
]

In [43]:
# Date consistency flags
df_sold_clean['listing_after_close_flag'] = df_sold_clean['ListingContractDate'] > df_sold_clean['CloseDate']
df_sold_clean['purchase_after_close_flag'] = df_sold_clean['PurchaseContractDate'] > df_sold_clean['CloseDate']
df_sold_clean['negative_timeline_flag'] = df_sold_clean['PurchaseContractDate'] < df_sold_clean['ListingContractDate']

print("Listing after close:", df_sold_clean['listing_after_close_flag'].sum())
print("Purchase after close:", df_sold_clean['purchase_after_close_flag'].sum())
print("Negative timeline:", df_sold_clean['negative_timeline_flag'].sum())

Listing after close: 78
Purchase after close: 13
Negative timeline: 213

In [44]:
# Geographic flags
df_sold_clean['missing_coords_flag'] = df_sold_clean['Latitude'].isnull() | df_sold_clean['Longitude'].isnull()
df_sold_clean['zero_coords_flag'] = (df_sold_clean['Latitude'] == 0) | (df_sold_clean['Longitude'] == 0)
df_sold_clean['invalid_longitude_flag'] = df_sold_clean['Longitude'] > 0

print("Missing coords:", df_sold_clean['missing_coords_flag'].sum())
print("Zero coords:", df_sold_clean['zero_coords_flag'].sum())
print("Invalid longitude:", df_sold_clean['invalid_longitude_flag'].sum())

Missing coords: 1312
Zero coords: 20
Invalid longitude: 36

In [45]:
# Final row counts
print("Final sold rows:", len(df_sold_clean))
print("Final listed rows:", len(df_listed_clean))

Final sold rows: 164406
Final listed rows: 239785

In [46]:
# Data types check
print(df_sold_clean.dtypes)

BuyerAgentAOR                object
ListAgentAOR                 object
Flooring                     object
ViewYN                       object
PoolPrivateYN                object
                              ...
purchase_after_close_flag      bool
negative_timeline_flag         bool
missing_coords_flag            bool
zero_coords_flag               bool
invalid_longitude_flag         bool
Length: 69, dtype: object

In [47]:
# Save cleaned datasets
df_sold_clean.to_csv("cleaned_sold.csv", index=False)
df_listed_clean.to_csv("cleaned_listed.csv", index=False)